# Generated by Django 4.1 on 2022-08-24 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogpel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_dead', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32)),
                ('resume', models.TextField(help_text='Pon aqui de que va la pelicula', max_length=300)),
                ('isan', models.CharField(help_text='pon aqui el ISAN de la pelicula', max_length=23, verbose_name='ISAN')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogpel.autor')),
                ('genero', models.ManyToManyField(to='catalogpel.genero')),
            ],
        ),
        migrations.CreateModel(
            name='peliculaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico para este libro', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'mantenimient'), ('o', 'on loan'), ('a', 'avalaible'), ('r', 'reserverd')], default='m', help_text='estado de la pelicula', max_length=1)),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogpel.pelicula')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
